kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: python:3.10
    commands:
      - pip install -r requirements.txt

  - name: publish
    image: plugins/docker
    settings:
      repo: magalixcorp/k8scicd
      tags: [ "aa","latest" ]
      username: "udpautocrypt"
      password: "udpautocrypt123"

# - name: deploy
#  image: sinlead/drone-kubectl
#  settings:
#    kubernetes_server:
#      from_secret: k8s_server
#    kubernetes_cert:
#      from_secret: k8s_cert
#    kubernetes_token:
#      from_secret: k8s_token
#  commands:
#    - kubectl apply -f deployment.yml