kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - sleep 5
      - docker build . -t connector-dev:latest

  - name: publish
    image: plugins/docker
    settings:
      repo: magalixcorp/k8scicd
      tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
      username: "udpautocrypt"
      password: "udpautocrypt123"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

# - name: deploy
#  image: sinlead/drone-kubectl
#  settings:
#    kubernetes_server:
#      from_secret: k8s_server
#    kubernetes_cert:
#      from_secret: k8s_cert
#    kubernetes_token:
#      from_secret: k8s_token
#  commands:
#    - kubectl apply -f deployment.yml