kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: python:3.10
    commands:
      - pip install -r requirements.txt

  - name: publish
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands: 
      - docker ps
      # - docker tag ...
      # - docker push ...

  # - name: publish
  #   image: plugins/docker
  #   settings:
  #     repo: udpautocrypt/connector
  #     tags: [ "${DRONE_COMMIT_SHA:0:7}" ]
  #     file: Dockerfile
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password


  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl apply -f connector-deployment.yml

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock